name: CI

on:
  push:
    branches: ['**']
    tags: ['v**']

env:
  DENO_VERSION: 2.8.3

jobs:
  health:
    name: health
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2.0.3
        with:
          deno-version: ${{ env.DENO_VERSION }}

      - run: deno lint
      - run: deno fmt --check
      - run: deno check lib/*.ts

      - run: deno test --no-check --coverage
      - run: deno coverage

  dryrun:
    needs: [health]
    name: 'publish (dry run)'
    if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2.0.3
        with:
          deno-version: ${{ env.DENO_VERSION }}
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 26
          registry-url: 'https://registry.npmjs.org'

      - run: deno task build
      - run: |
          npm version patch
          npm stage publish --dry-run
        working-directory: npm
      - run: deno publish --no-check --dry-run

  # https://jsr.io/docs/publishing-packages#publishing-from-github-actions
  # https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-to-the-npm-registry
  publish:
    needs: [health]
    name: publish
    runs-on: ubuntu-24.04-arm
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: read
      id-token: write # -> authentication
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2.0.3
        with:
          deno-version: ${{ env.DENO_VERSION }}
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 26
          registry-url: 'https://registry.npmjs.org'

      - run: deno task build

      - name: 'Publish → jsr'
        if: ${{ !contains(github.ref, '-next.') }}
        run: deno publish --no-check

      - name: 'Publish → npm'
        if: ${{ !contains(github.ref, '-next.') }}
        run: npm stage publish --provenance --access public
        working-directory: npm

      - name: 'Publish → npm (pre-release)'
        if: ${{ contains(github.ref, '-next.') }}
        run: npm stage publish --tag next --provenance --access public
        working-directory: npm
